# Generated by Django 5.0.3 on 2024-06-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesskey',
            name='key',
            field=models.CharField(default='', max_length=16, unique=True),
        ),
    ]
