# Generated by Django 5.0.6 on 2024-06-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0003_customuser_other_names_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesskey',
            name='revoked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
