# Generated by Django 5.0.6 on 2024-06-14 02:23

import keys.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0006_alter_accesskey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='key',
            field=models.CharField(default=keys.utils.generate_random_string, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=10),
        ),
    ]
