# Generated by Django 5.0.6 on 2024-06-19 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0008_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='other_names',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
